# Generated by Django 4.1 on 2022-12-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Urgent',
            field=models.BooleanField(default=False),
        ),
    ]
