# Generated by Django 4.1 on 2022-12-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_urgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Urgent',
            new_name='urgent',
        ),
    ]
