# Generated by Django 4.1 on 2022-12-28 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_team_moderator_team_owner_alter_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='moderator',
            field=models.ManyToManyField(null=True, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
