# Generated by Django 4.1 on 2023-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_moderatoradd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorAdd',
        ),
    ]
